version: '3.9'

services:
  db:
    image: mysql:8.0.26
    platform: linux/x86_64 # Necessary for running on M1 Macs
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:?err}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:?err}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data: