filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "itu-minitwit-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.or:
        - contains:
            container.image.name: christiangerdes/minitwitimage
        - contains:
            container.image.name: itu-minitwit_server
        - contains:
            container.image.name: ${CONTAINER_PREFIX:?err}/minitwitserver

logging.json: true
logging.metrics.enabled: false


