global:
  scrape_interval:     60s
  evaluation_interval: 60s

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  # Create a job for Docker daemons.
  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # Set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

  - job_name: webserver 
    metrics_path: /metrics
    static_configs:
      - targets:
        - minitwit:8080

  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080