$install_docker_script = <<SCRIPT
echo Installing Docker...
curl -sSL https://get.docker.com/ | sh
sudo usermod -aG docker ubuntu
SCRIPT

$manager_script = <<SCRIPT
echo Swarm Init...
sudo docker swarm init --listen-addr 10.100.199.200:2377 --advertise-addr 10.100.199.200:2377
sudo docker swarm join-token --quiet worker > /vagrant/worker_token
SCRIPT

$worker_script = <<SCRIPT
echo Swarm Join...
sudo docker swarm join --token $(cat /vagrant/worker_token) 10.100.199.200:2377
SCRIPT

$ufw_script = <<SCRIPT
ufw allow 22/tcp && ufw allow 2376/tcp && ufw allow 2377/tcp && ufw allow 7946/tcp && ufw allow 7946/udp && ufw allow 4789/udp && ufw reload && ufw --force  enable 
echo "\n\n\n\n\n\nshit\n\n\n\n\n\n"
SCRIPT
# && systemctl restart docker

Vagrant.configure('2') do |config|
    vm_box = "digital_ocean"
	vm_box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
	ssh_private_path = './minitwit'
    config.env.enable
	#config.ssh.private_key_path = ssh_private_path
    config.vm.define :manager, primary: true  do |manager|
        manager.vm.box = vm_box
        manager.vm.box_url = vm_box_url
        manager.ssh.private_key_path = ssh_private_path
        manager.vm.box_check_update = true
        manager.vm.network :private_network, ip: "10.100.199.200"
        manager.vm.network :forwarded_port, guest: 8080, host: 8080
        manager.vm.network :forwarded_port, guest: 5000, host: 5000
        manager.vm.hostname = "manager"
        manager.vm.synced_folder "../remote_files", "/vagrant"
        # manager.vm.provision "shell", inline: $install_docker_script, privileged: true
        manager.vm.provision "shell", inline: $ufw_script, privileged: true
        manager.vm.provision "shell", inline: $manager_script, privileged: true
        manager.vm.provider "digital_ocean" do |vb|
            vb.name = "manager"
            vb.ssh_key_name = 'do_ssh_key'
            vb.token = ENV["DOTOKEN"]
            vb.image = 'docker-18-04'
            vb.region = 'fra1'
            vb.size = 's-1vcpu-1gb'
            vb.privatenetworking = true
        end
    end
    (1..2).each do |i|
        config.vm.define "worker0#{i}" do |worker|
            worker.vm.box = vm_box
            worker.vm.box_url = vm_box_url
            worker.ssh.private_key_path = ssh_private_path
            worker.vm.box_check_update = true
            worker.vm.network :private_network, ip: "10.100.199.20#{i}"
            worker.vm.hostname = "worker0#{i}"
            worker.vm.synced_folder ".", "/vagrant"
            #worker.vm.provision "shell", inline: $install_docker_script, privileged: true
            worker.vm.provision "shell", inline: $ufw_script, privileged: true
            worker.vm.provision "shell", inline: $worker_script, privileged: true
            worker.vm.provider "digital_ocean" do |vb|
                vb.name = "worker0#{i}"
                vb.ssh_key_name = 'do_ssh_key'
                vb.token = ENV["DOTOKEN"]
                vb.image = 'docker-18-04'
                vb.region = 'fra1'
                vb.size = 's-1vcpu-1gb'
                vb.privatenetworking = true
            end
        end
    end
end