global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: golang 
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:8080

  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080