version: '3.9'

volumes:
  grafana-storage:
  prometheus_data:
  db_data:

networks:
  app-network:

services:
  server:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADDRESS=${MYSQL_ADDRESS}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - '8080:8080' # docker port : localhost port
    networks:
      - app-network

  client:
    image: ${DOCKER_USERNAME}/minitwit-client
    container_name: minitwit
    ports:
      - 4000:80

  grafana:
    image: grafana/grafana-oss:8.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: 0
      GF_AUTH_ANONYMOUS_ENABLED: 1

  prometheus:
    image: prom/prometheus:v2.24.0
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor:v0.24.1
    privileged: true
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
