version: '3.9'


networks:
  app-network:
   
services:
  server:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit

    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ADDRESS=${MYSQL_ADDRESS}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - '8080:8080' # docker port : localhost port
    networks:
      - app-network
