version: "3.9"

#Docker Networks
networks:
  app-network:

#Volumes
# volumes:
#   db_data:

services: 
  db:
    image: mysql:8
    platform: linux/x86_64 # Necessary for running on M1 Macs
    container_name: db
    restart: always
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=${MYSQL_USER}
      # You can use whatever password you like
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # Password for root access
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db/configs/:/docker-entrypoint-initdb.d/
    networks:
      - app-network
      
  server:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    ports:
      - "8080:8080"   # docker port : localhost port
    depends_on:
      - db
    networks:
      - app-network

  