{
 "title": "Minitwit dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Web server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Simulator endpoints response time, 99th quantile",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, http_response_time_seconds_bucket{path=~\"/api/(msgs/.*?|fllws/.*?|register|latest)\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Non-simulator endpoints response time, 99th quantile",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, http_response_time_seconds_bucket{path=~\"/api/(timeline|users.*|tweets|signin|metrics)\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Simulator endpoints response time, 99th quantile, historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, http_response_time_seconds_bucket{path=~\"/api/(msgs/.*?|fllws/.*?|register|latest)\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Non-simulator endpoints response time, 99th quantile, historical",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, http_response_time_seconds_bucket{path=~\"/api/(timeline|users.*|tweets|signin|metrics)\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Response status codes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "response_status", "legendFormat": "{{status}}" }
   ]
  },
  { "title": "Container statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Average CPU time consumed per second in past minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"[a-zA-Z0-9_-]+\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"[a-zA-Z0-9_-]+\"}",
     "legendFormat": "{{name}} "
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Database uptime since last boot",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gorm_status_Uptime", "legendFormat": "Uptime" }
   ]
  },
  {
   "title": "Database stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    { "expr": "gorm_dbstats_idle", "legendFormat": "Idle connections" },
    { "expr": "gorm_dbstats_in_use", "legendFormat": "Active connections" },
    { "expr": "gorm_status_Slow_queries", "legendFormat": "Slow queries" },
    { "expr": "gorm_status_Threads_running", "legendFormat": "Threads running" }
   ]
  },
  { "title": "Business Intellegence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Average followers per user",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_average_followers_count",
     "legendFormat": "Average followers per user"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minitwit_total_users_count", "legendFormat": "Total users" }
   ]
  }
 ]
}