name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build:
  #   name: "Build and push"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v2

  #     - name: Login to Dockerhub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push api docker image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/minitwitimage:latest . -f ./server/Dockerfile
  #         docker push ${{ secrets.DOCKER_USERNAME }}/minitwitimage:latest

  #     - name: Build and push client docker image
  #       run: |
  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/minitwit-client:latest . -f ./client/Dockerfile
  #         docker push ${{ secrets.DOCKER_USERNAME }}/minitwit-client:latest

  scan:
    name: "Scan the container"
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/container-scan@v0
        with:
          image-name: ${{ secrets.DOCKER_USERNAME }}/minitwitimage:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  copy:
    name: "Copy docker-compose file"
    # needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        key: ${{ secrets.XSSH_PRIVATE_KEY }}
        host: ${{ secrets.XSERVER_IP }}
        username: ${{ secrets.XSERVER_USER }}
        port: 22
        strip_components: 2
        source: "./swarm/docker-compose.yml, ./swarm/filebeat.yml, ./swarm/grafana/, ./swarm/prometheus/"
        target: "/root"

  deploy:
    name: "Deploy to droplet"
    needs: copy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.4
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_DATABASE: ${{ secrets.XMYSQL_DATABASE }}
          MYSQL_PASSWORD: ${{ secrets.XMYSQL_PASSWORD }}
          MYSQL_ADDRESS: ${{ secrets.XMYSQL_ADDRESS }}
          MYSQL_PORT: 25060
          GRAFANA_ADMIN_USERNAME: ${{ secrets.GRAFANA_ADMIN_USERNAME }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
          ELK_USER: ${{ secrets.ELK_USER }}
          ELASTIC_USER: ${{ secrets.ELASTIC_USER }}
          ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          STACK_NAME: ${{ secrets.STACK_NAME }}
        with:
          key: ${{ secrets.XSSH_PRIVATE_KEY }}
          host: ${{ secrets.XSERVER_IP }}
          username: ${{ secrets.XSERVER_USER }}
          port: 22
          envs: DOCKER_USERNAME,MYSQL_USER,MYSQL_DATABASE,MYSQL_PORT,GRAFANA_ADMIN_USERNAME,GRAFANA_ADMIN_PASSWORD,ELK_USER,ELASTIC_USER,ELASTIC_PASSWORD,STACK_NAME,ACCESS_KEY,SECRET_KEY,BUCKET_NAME
          script: |
            cd /root

            export DOCKER_USERNAME=$DOCKER_USERNAME
            export MYSQL_USER=$MYSQL_USER
            export MYSQL_DATABASE=$MYSQL_DATABASE
            export MYSQL_PASSWORD=$MYSQL_PASSWORD
            export MYSQL_ADDRESS=$MYSQL_ADDRESS
            export MYSQL_PORT=$MYSQL_PORT
            export GRAFANA_ADMIN_USERNAME=$GRAFANA_ADMIN_USERNAME
            export GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
            export ELK_USER=$ELK_USER
            export ELASTIC_USER=$ELASTIC_USER
            export ELASTIC_PASSWORD=$ELASTIC_PASSWORD
            export STACK_NAME=$STACK_NAME
            export ACCESS_KEY=$ACCESS_KEY
            export SECRET_KEY=$SECRET_KEY
            export BUCKET_NAME=$BUCKET_NAME


            docker-compose pull
            docker stack deploy --compose-file docker-compose.yml $STACK_NAME

  # versioning:
  #   name: "Tag and release"
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Bump version and push tag
  #       id: tag_version
  #       uses: mathieudutour/github-tag-action@v6.0
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         default_bump: major
  #     - name: Create a GitHub release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         tag: ${{ steps.tag_version.outputs.new_tag }}
  #         name: Release ${{ steps.tag_version.outputs.new_tag }}
  #         body: ${{ steps.tag_version.outputs.changelog }}