name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd ./report
            pdflatex main
            biber main
            pdflatex main
            pdflatex main
            latexmk -c
      - name: commit
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          ls
          pwd
          git commit -am "pdf"