name: Provision server

on: 
  workflow_dispatch:

jobs: 
  provision:
    name: Provision
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Download jq
        uses: sergeysova/jq-action@v2

      - name: Download Terraform
        uses: hashicorp/setup-terraform@v2

      - name: start provision script
        working-directory: ./terraform
        run: |
          echo "Setting backend secrets"

          export ACCESS_KEY=${{ secrets.ACCESS_KEY }}
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          export STATE_FILE=${{ secrets.STATE_FILE }}
          export BUCKET_NAME=${{ secrets.BUCKET_NAME }}

          echo "Setting other secrets"

          export TF_VAR_do_token=${{ secrets.TF_VAR_DO_TOKEN }}
          export TF_VAR_state_file=STATE_FILE
          export TF_VAR_manager_ip=${{ secrets.XSERVER_IP }}
          export TF_VAR_bucket_name=BUCKET_NAME
          export TF_VAR_access_key=ACCESS_KEY
          export TF_VAR_secret_key=SECRET_KEY
          export TF_VAR_stack_name=${{ secrets.STACK_NAME }}
          export TF_VAR_prometheus_backup_interval=${{ secrets.PROMETHEUS_BACKUP_INTERVAL }}
          export TF_VAR_space_endpoint=${{ secrets.SPACE_ENDPOINT }}

          echo $PRIV_KEY
          echo $PUB_KEY
          echo "------"
          echo $TF_VAR_do_token
          echo ${{ secrets.TF_VAR_DO_TOKEN }}
          echo "------"

          mkdir ssh_key
          pwd
          ls
          echo "Created dir"
          echo ${{ secrets.PROV_SSH_PUBLIC }} | base64 -d > ./ssh_key/terraform.pub
          echo "Created private key"
          echo ${{ secrets.PROV_SSH_PRIVATE }} | base64 -d > ./ssh_key/terraform
      
          echo "Reading public key"
          cat ./ssh_key/terraform.pub

          echo "Reading private key"
          cat ./ssh_key/terraform

          chmod +x ./bootstrap.sh
          echo "chmodded bootstrap"
          pwd
          ls
          sudo ./bootstrap.sh






