name: Static Analysis
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Format
        working-directory: ./server
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Examine source
        working-directory: ./server
        run: if [ "$(go vet)" -gt 0 ]; then exit 1; fi
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude=G104 ./...