name: Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - feature/run-test-job

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Configure Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build and test
        run: |
          cd server
          go build -v -o main .
          go test -v